"""
Vue single-file component backend adapter.

Generates Vue 3 SFCs (.vue files) with scoped CSS.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from ..protocol import (
    BackendAdapter,
    BackendCapabilities,
    Feature,
    FidelityLoss,
    GeneratedFile,
    GeneratedOutput,
    WEB_COMMON_FEATURES,
)
from core.ir_types import IRDocument
from core.layout_types import LayoutPlan
from core.resolver import ResolutionReport

_VUE_SUPPORTED = WEB_COMMON_FEATURES | frozenset({
    Feature.GRID,
    Feature.FILLS_GRADIENT,
    Feature.FILLS_IMAGE,
    Feature.SHADOWS,
    Feature.BLUR,
    Feature.CORNER_RADIUS,
    Feature.PER_CORNER_RADIUS,
    Feature.TEXT_DECORATION,
    Feature.TEXT_CASE,
    Feature.LETTER_SPACING,
    Feature.OVERFLOW_CLIP,
    Feature.OVERFLOW_SCROLL,
    Feature.IMAGE_ASSETS,
    Feature.SVG_ASSETS,
    Feature.DESIGN_TOKENS,
    Feature.TOKEN_REFERENCES,
    Feature.COMPONENTS,
    Feature.COMPONENT_INSTANCES,
    Feature.COMPONENT_VARIANTS,
    Feature.BREAKPOINTS,
    Feature.MEDIA_QUERIES,
    Feature.RESPONSIVE_CONSTRAINTS,
    Feature.PROTOTYPE_LINKS,
    Feature.INTERACTIONS,
})

_VUE_UNSUPPORTED = frozenset()

_VUE_PARTIAL = frozenset({
    Feature.CONSTRAINTS,
    Feature.MARGIN,
    Feature.AUTO_LAYOUT,
    Feature.ABSOLUTE_POSITIONING,
    Feature.RELATIVE_POSITIONING,
})


class VueBackend(BackendAdapter):
    """Vue 3 SFC backend.

    Generates Vue single-file components with <template>, <script setup>,
    and <style scoped> sections.  Design tokens map to CSS custom properties.
    """

    @property
    def name(self) -> str:
        return "vue"

    @property
    def display_name(self) -> str:
        return "Vue 3 SFC"

    @property
    def capabilities(self) -> BackendCapabilities:
        return BackendCapabilities(
            supported_features=_VUE_SUPPORTED,
            unsupported_features=_VUE_UNSUPPORTED,
            partial_features=_VUE_PARTIAL,
            styling_system="css_scoped",
            framework="vue",
            renderer="browser",
            file_extensions=(".vue",),
        )

    def generate(
        self,
        document: IRDocument,
        layout_plan: LayoutPlan,
        resolution: Optional[ResolutionReport] = None,
        viewport: float = 1440.0,
        options: Optional[Dict[str, Any]] = None,
    ) -> GeneratedOutput:
        output = GeneratedOutput()

        for screen_idx, screen in enumerate(layout_plan.screens):
            component_name = _to_pascal_case(screen.name or f"Screen{screen_idx}")
            vue_content = self._generate_sfc(screen, component_name)
            node_ids = [n.node_id for n in screen.walk() if n.node_id]

            output.files.append(GeneratedFile(
                path=f"{component_name}.vue",
                content=vue_content,
                language="vue",
                node_ids=node_ids,
            ))

        output.fidelity_losses.extend(self.preflight(document, layout_plan))
        output.metadata = {
            "backend": self.name,
            "viewport": viewport,
            "screen_count": len(layout_plan.screens),
        }
        return output

    def _generate_sfc(self, plan: Any, name: str) -> str:
        return f"""\
<template>
  <div class="{name.lower()}" data-figma-screen="{plan.name or name}">
    <!-- TODO: Generate from LayoutPlan for node {plan.node_id} -->
    <p>{name} — generated by FigmaForge Vue backend</p>
  </div>
</template>

<script setup lang="ts">
// FigmaForge generated Vue component
// Source: LayoutPlan node {plan.node_id}
defineProps<{{
  className?: string
}}>()
</script>

<style scoped>
.{name.lower()} {{
  /* TODO: Generate CSS from LayoutPlan */
}}
</style>
"""


def _to_pascal_case(name: str) -> str:
    parts = name.replace("-", " ").replace("_", " ").split()
    return "".join(p.capitalize() for p in parts) if parts else "Component"
