"""
Svelte component backend adapter.

Generates Svelte components (.svelte files) with scoped styles.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from ..protocol import (
    BackendAdapter,
    BackendCapabilities,
    Feature,
    FidelityLoss,
    GeneratedFile,
    GeneratedOutput,
    WEB_COMMON_FEATURES,
)
from core.ir_types import IRDocument
from core.layout_types import LayoutPlan
from core.resolver import ResolutionReport

_SVELTE_SUPPORTED = WEB_COMMON_FEATURES | frozenset({
    Feature.GRID,
    Feature.FILLS_GRADIENT,
    Feature.FILLS_IMAGE,
    Feature.SHADOWS,
    Feature.BLUR,
    Feature.CORNER_RADIUS,
    Feature.PER_CORNER_RADIUS,
    Feature.TEXT_DECORATION,
    Feature.TEXT_CASE,
    Feature.LETTER_SPACING,
    Feature.OVERFLOW_CLIP,
    Feature.OVERFLOW_SCROLL,
    Feature.IMAGE_ASSETS,
    Feature.SVG_ASSETS,
    Feature.DESIGN_TOKENS,
    Feature.TOKEN_REFERENCES,
    Feature.COMPONENTS,
    Feature.COMPONENT_INSTANCES,
    Feature.COMPONENT_VARIANTS,
    Feature.BREAKPOINTS,
    Feature.MEDIA_QUERIES,
    Feature.RESPONSIVE_CONSTRAINTS,
    Feature.PROTOTYPE_LINKS,
    Feature.INTERACTIONS,
})

_SVELTE_PARTIAL = frozenset({
    Feature.CONSTRAINTS,
    Feature.MARGIN,
    Feature.AUTO_LAYOUT,
    Feature.ABSOLUTE_POSITIONING,
    Feature.RELATIVE_POSITIONING,
})


class SvelteBackend(BackendAdapter):
    """Svelte component backend.

    Generates Svelte components with scoped <style> blocks.
    Design tokens map to CSS custom properties.
    """

    @property
    def name(self) -> str:
        return "svelte"

    @property
    def display_name(self) -> str:
        return "Svelte"

    @property
    def capabilities(self) -> BackendCapabilities:
        return BackendCapabilities(
            supported_features=_SVELTE_SUPPORTED,
            unsupported_features=frozenset(),
            partial_features=_SVELTE_PARTIAL,
            styling_system="css_scoped",
            framework="svelte",
            renderer="browser",
            file_extensions=(".svelte",),
        )

    def generate(
        self,
        document: IRDocument,
        layout_plan: LayoutPlan,
        resolution: Optional[ResolutionReport] = None,
        viewport: float = 1440.0,
        options: Optional[Dict[str, Any]] = None,
    ) -> GeneratedOutput:
        output = GeneratedOutput()

        for screen_idx, screen in enumerate(layout_plan.screens):
            component_name = _to_pascal_case(screen.name or f"Screen{screen_idx}")
            svelte_content = self._generate_component(screen, component_name)
            node_ids = [n.node_id for n in screen.walk() if n.node_id]

            output.files.append(GeneratedFile(
                path=f"{component_name}.svelte",
                content=svelte_content,
                language="svelte",
                node_ids=node_ids,
            ))

        output.fidelity_losses.extend(self.preflight(document, layout_plan))
        output.metadata = {
            "backend": self.name,
            "viewport": viewport,
            "screen_count": len(layout_plan.screens),
        }
        return output

    def _generate_component(self, plan: Any, name: str) -> str:
        return f"""\
<script lang="ts">
  // FigmaForge generated Svelte component
  // Source: LayoutPlan node {plan.node_id}
  export let className: string = '';
</script>

<div class="{name.lower()} {{className}}" data-figma-screen="{plan.name or name}">
  <!-- TODO: Generate from LayoutPlan for node {plan.node_id} -->
  <p>{name} — generated by FigmaForge Svelte backend</p>
</div>

<style>
  .{name.lower()} {{
    /* TODO: Generate CSS from LayoutPlan */
  }}
</style>
"""


def _to_pascal_case(name: str) -> str:
    parts = name.replace("-", " ").replace("_", " ").split()
    return "".join(p.capitalize() for p in parts) if parts else "Component"
